# Error pattern recognition rules
ModuleNotFoundError:
  action: check_requirements
  severity: medium
  description: "Missing Python module"
  auto_fix: true
  retry_count: 3
  retry_delay: 5

ConnectionError:
  action: check_services
  severity: high
  description: "Service connection failure"
  auto_fix: true
  retry_count: 5
  retry_delay: 10

ValueError:
  action: validate_data
  severity: low
  description: "Invalid data value"
  auto_fix: true
  retry_count: 2
  retry_delay: 1

JSONDecodeError:
  action: clean_payload
  severity: low
  description: "Malformed JSON data"
  auto_fix: true
  retry_count: 2
  retry_delay: 1

ImportError:
  action: check_requirements
  severity: medium
  description: "Module import failure"
  auto_fix: true
  retry_count: 3
  retry_delay: 5

AttributeError:
  action: auto_fix_code
  severity: medium
  description: "Invalid attribute access"
  auto_fix: true
  retry_count: 2
  retry_delay: 1

TypeError:
  action: validate_data
  severity: low
  description: "Type mismatch"
  auto_fix: true
  retry_count: 2
  retry_delay: 1

KeyError:
  action: validate_data
  severity: low
  description: "Missing dictionary key"
  auto_fix: true
  retry_count: 2
  retry_delay: 1

IndexError:
  action: validate_data
  severity: low
  description: "Invalid list index"
  auto_fix: true
  retry_count: 2
  retry_delay: 1

FileNotFoundError:
  action: check_services
  severity: medium
  description: "Missing file or directory"
  auto_fix: true
  retry_count: 3
  retry_delay: 5

PermissionError:
  action: check_services
  severity: high
  description: "Permission denied"
  auto_fix: false
  retry_count: 1
  retry_delay: 0

TimeoutError:
  action: check_services
  severity: medium
  description: "Operation timed out"
  auto_fix: true
  retry_count: 3
  retry_delay: 5

MemoryError:
  action: check_services
  severity: high
  description: "Out of memory"
  auto_fix: false
  retry_count: 1
  retry_delay: 0

RecursionError:
  action: auto_fix_code
  severity: high
  description: "Maximum recursion depth exceeded"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

NotImplementedError:
  action: auto_fix_code
  severity: medium
  description: "Feature not implemented"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

AssertionError:
  action: auto_fix_code
  severity: medium
  description: "Assertion failed"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

RuntimeError:
  action: auto_fix_code
  severity: high
  description: "Runtime error"
  auto_fix: true
  retry_count: 2
  retry_delay: 1

OSError:
  action: check_services
  severity: high
  description: "Operating system error"
  auto_fix: false
  retry_count: 3
  retry_delay: 5

IOError:
  action: check_services
  severity: medium
  description: "Input/output error"
  auto_fix: true
  retry_count: 3
  retry_delay: 5

SyntaxError:
  action: auto_fix_code
  severity: high
  description: "Syntax error"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

IndentationError:
  action: auto_fix_code
  severity: high
  description: "Indentation error"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

NameError:
  action: auto_fix_code
  severity: medium
  description: "Undefined variable"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

UnboundLocalError:
  action: auto_fix_code
  severity: medium
  description: "Unbound local variable"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

ZeroDivisionError:
  action: validate_data
  severity: low
  description: "Division by zero"
  auto_fix: true
  retry_count: 2
  retry_delay: 1

OverflowError:
  action: validate_data
  severity: medium
  description: "Numeric overflow"
  auto_fix: true
  retry_count: 2
  retry_delay: 1

FloatingPointError:
  action: validate_data
  severity: low
  description: "Floating point error"
  auto_fix: true
  retry_count: 2
  retry_delay: 1

ArithmeticError:
  action: validate_data
  severity: low
  description: "Arithmetic error"
  auto_fix: true
  retry_count: 2
  retry_delay: 1

BufferError:
  action: check_services
  severity: high
  description: "Buffer error"
  auto_fix: false
  retry_count: 1
  retry_delay: 0

LookupError:
  action: validate_data
  severity: low
  description: "Lookup error"
  auto_fix: true
  retry_count: 2
  retry_delay: 1

ReferenceError:
  action: auto_fix_code
  severity: medium
  description: "Reference error"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

SystemError:
  action: check_services
  severity: high
  description: "System-level error"
  auto_fix: true
  retry_count: 3
  retry_delay: 5
  recovery_strategy: "restart_service"
  monitoring: true
  circuit_breaker:
    threshold: 5
    timeout: 300
    half_open_timeout: 60
  fallback_strategy: "degrade_service"

TypeError:
  action: validate_data
  severity: low
  description: "Type error"
  auto_fix: true
  retry_count: 2
  retry_delay: 1
  recovery_strategy: "convert_and_retry"
  monitoring: false

ValueError:
  action: validate_data
  severity: low
  description: "Value error"
  auto_fix: true
  retry_count: 2
  retry_delay: 1
  recovery_strategy: "validate_and_retry"
  monitoring: false

Warning:
  action: validate_data
  severity: low
  description: "Warning"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

UserWarning:
  action: validate_data
  severity: low
  description: "User warning"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

DeprecationWarning:
  action: auto_fix_code
  severity: low
  description: "Deprecation warning"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

PendingDeprecationWarning:
  action: auto_fix_code
  severity: low
  description: "Pending deprecation warning"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

SyntaxWarning:
  action: auto_fix_code
  severity: low
  description: "Syntax warning"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

RuntimeWarning:
  action: auto_fix_code
  severity: low
  description: "Runtime warning"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

FutureWarning:
  action: auto_fix_code
  severity: low
  description: "Future warning"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

ImportWarning:
  action: check_requirements
  severity: low
  description: "Import warning"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

UnicodeWarning:
  action: validate_data
  severity: low
  description: "Unicode warning"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

BytesWarning:
  action: validate_data
  severity: low
  description: "Bytes warning"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

ResourceWarning:
  action: check_services
  severity: low
  description: "Resource warning"
  auto_fix: true
  retry_count: 1
  retry_delay: 0

# Network and connectivity errors
ConnectionError:
  action: check_services
  severity: high
  description: "Network connection error"
  auto_fix: true
  retry_count: 5
  retry_delay: 2
  recovery_strategy: "reconnect"
  monitoring: true
  circuit_breaker:
    threshold: 3
    timeout: 180
    half_open_timeout: 30
  fallback_strategy: "use_cached_data"
  load_balancing: true

TimeoutError:
  action: check_services
  severity: medium
  description: "Operation timeout"
  auto_fix: true
  retry_count: 3
  retry_delay: 1
  recovery_strategy: "retry_with_backoff"
  monitoring: true

# Database errors
DatabaseError:
  action: check_services
  severity: high
  description: "Database error"
  auto_fix: true
  retry_count: 3
  retry_delay: 2
  recovery_strategy: "reconnect_db"
  monitoring: true
  circuit_breaker:
    threshold: 3
    timeout: 120
    half_open_timeout: 20
  fallback_strategy: "use_read_replica"
  connection_pool:
    min_size: 5
    max_size: 20
    timeout: 30

IntegrityError:
  action: validate_data
  severity: medium
  description: "Database integrity error"
  auto_fix: true
  retry_count: 2
  retry_delay: 1
  recovery_strategy: "rollback_and_retry"
  monitoring: true

# Application errors
ValidationError:
  action: validate_data
  severity: low
  description: "Data validation error"
  auto_fix: true
  retry_count: 2
  retry_delay: 1
  recovery_strategy: "clean_and_retry"
  monitoring: false
  validation_rules:
    strict: true
    custom_validators: true
    schema_validation: true

# Resource errors
MemoryError:
  action: check_services
  severity: high
  description: "Memory error"
  auto_fix: true
  retry_count: 2
  retry_delay: 5
  recovery_strategy: "cleanup_memory"
  monitoring: true
  circuit_breaker:
    threshold: 2
    timeout: 60
    half_open_timeout: 10
  fallback_strategy: "degrade_features"
  memory_management:
    gc_threshold: 80
    cache_clear_threshold: 70
    aggressive_cleanup: true

ResourceError:
  action: check_services
  severity: high
  description: "Resource error"
  auto_fix: true
  retry_count: 3
  retry_delay: 2
  recovery_strategy: "cleanup_resources"
  monitoring: true

# Security errors
AuthenticationError:
  action: check_services
  severity: high
  description: "Authentication error"
  auto_fix: false
  retry_count: 1
  retry_delay: 0
  recovery_strategy: "reauthenticate"
  monitoring: true
  circuit_breaker:
    threshold: 3
    timeout: 300
    half_open_timeout: 60
  fallback_strategy: "use_alternative_auth"
  auth_management:
    token_refresh: true
    session_management: true
    mfa_fallback: true

AuthorizationError:
  action: check_services
  severity: high
  description: "Authorization error"
  auto_fix: false
  retry_count: 1
  retry_delay: 0
  recovery_strategy: "check_permissions"
  monitoring: true

SecurityError:
  action: check_services
  severity: critical
  description: "Security error"
  auto_fix: false
  retry_count: 1
  retry_delay: 0
  recovery_strategy: "block_and_alert"
  monitoring: true
  circuit_breaker:
    threshold: 1
    timeout: 3600
    half_open_timeout: 300
  fallback_strategy: "emergency_shutdown"
  security_measures:
    ip_blocking: true
    rate_limiting: true
    alert_threshold: 1

# Service-specific errors
ServiceUnavailableError:
  action: check_services
  severity: high
  description: "Service unavailable"
  auto_fix: true
  retry_count: 5
  retry_delay: 2
  recovery_strategy: "restart_service"
  monitoring: true
  circuit_breaker:
    threshold: 3
    timeout: 180
    half_open_timeout: 30
  fallback_strategy: "use_backup_service"
  service_discovery:
    enabled: true
    health_check_interval: 30
    timeout: 5

ServiceTimeoutError:
  action: check_services
  severity: medium
  description: "Service timeout"
  auto_fix: true
  retry_count: 3
  retry_delay: 1
  recovery_strategy: "retry_with_backoff"
  monitoring: true

# Configuration errors
ConfigurationError:
  action: check_services
  severity: high
  description: "Configuration error"
  auto_fix: true
  retry_count: 2
  retry_delay: 1
  recovery_strategy: "reload_config"
  monitoring: true
  circuit_breaker:
    threshold: 2
    timeout: 60
    half_open_timeout: 10
  fallback_strategy: "use_default_config"
  config_management:
    backup: true
    versioning: true
    validation: true

# File system errors
FileNotFoundError:
  action: check_services
  severity: medium
  description: "File not found"
  auto_fix: true
  retry_count: 2
  retry_delay: 1
  recovery_strategy: "create_file"
  monitoring: true

PermissionError:
  action: check_services
  severity: high
  description: "Permission error"
  auto_fix: false
  retry_count: 1
  retry_delay: 0
  recovery_strategy: "check_permissions"
  monitoring: true

# API errors
APIError:
  action: check_services
  severity: medium
  description: "API error"
  auto_fix: true
  retry_count: 3
  retry_delay: 2
  recovery_strategy: "retry_api_call"
  monitoring: true

RateLimitError:
  action: check_services
  severity: medium
  description: "Rate limit exceeded"
  auto_fix: true
  retry_count: 3
  retry_delay: 5
  recovery_strategy: "wait_and_retry"
  monitoring: true
  circuit_breaker:
    threshold: 3
    timeout: 60
    half_open_timeout: 10
  fallback_strategy: "queue_request"
  rate_limiting:
    adaptive: true
    burst_handling: true
    priority_queuing: true

# Performance errors
PerformanceError:
  action: check_services
  severity: medium
  description: "Performance degradation"
  auto_fix: true
  retry_count: 2
  retry_delay: 5
  recovery_strategy: "optimize_performance"
  monitoring: true
  circuit_breaker:
    threshold: 3
    timeout: 300
    half_open_timeout: 60
  fallback_strategy: "throttle_requests"
  performance_optimization:
    cache_optimization: true
    query_optimization: true
    resource_cleanup: true

# Integration errors
IntegrationError:
  action: check_services
  severity: high
  description: "External service integration error"
  auto_fix: true
  retry_count: 3
  retry_delay: 2
  recovery_strategy: "retry_with_backoff"
  monitoring: true
  circuit_breaker:
    threshold: 3
    timeout: 180
    half_open_timeout: 30
  fallback_strategy: "use_cached_response"
  integration_management:
    timeout: 30
    retry_policy: "exponential"
    fallback_enabled: true

# Error patterns configuration

# System errors
SystemError:
  action: "restart_service"
  severity: "critical"
  description: "System-level error requiring service restart"
  auto_fix: true
  retry_count: 3
  retry_delay: 5
  recovery_strategy: "service_restart"
  monitoring:
    enabled: true
    alert: true
  circuit_breaker:
    enabled: true
    failure_threshold: 3
  fallback_strategy: "degrade_service"

# Connection errors
ConnectionError:
  action: "reconnect"
  severity: "high"
  description: "Connection failure to external service"
  auto_fix: true
  retry_count: 5
  retry_delay: 2
  recovery_strategy: "retry_with_backoff"
  monitoring:
    enabled: true
    alert: true
  circuit_breaker:
    enabled: true
    failure_threshold: 5
  fallback_strategy: "use_backup_service"

# Database errors
DatabaseError:
  action: "reconnect_db"
  severity: "high"
  description: "Database connection or query error"
  auto_fix: true
  retry_count: 3
  retry_delay: 5
  recovery_strategy: "db_reconnect"
  monitoring:
    enabled: true
    alert: true
  circuit_breaker:
    enabled: true
    failure_threshold: 3
  fallback_strategy: "use_read_replica"

# Memory errors
MemoryError:
  action: "cleanup_memory"
  severity: "high"
  description: "Memory usage exceeded threshold"
  auto_fix: true
  retry_count: 2
  retry_delay: 1
  recovery_strategy: "memory_cleanup"
  monitoring:
    enabled: true
    alert: true
  circuit_breaker:
    enabled: false
  fallback_strategy: "degrade_features"
  memory_management:
    threshold: 80
    cleanup_aggressive: true

# Security errors
SecurityError:
  action: "block_and_alert"
  severity: "critical"
  description: "Security violation detected"
  auto_fix: false
  retry_count: 0
  retry_delay: 0
  recovery_strategy: "block_and_alert"
  monitoring:
    enabled: true
    alert: true
  circuit_breaker:
    enabled: false
  fallback_strategy: "use_alternative_auth"
  security_management:
    block_duration: 3600
    notify_admin: true
    log_incident: true

# Service unavailable errors
ServiceUnavailableError:
  action: "retry"
  severity: "high"
  description: "Service temporarily unavailable"
  auto_fix: true
  retry_count: 5
  retry_delay: 3
  recovery_strategy: "retry_with_backoff"
  monitoring:
    enabled: true
    alert: true
  circuit_breaker:
    enabled: true
    failure_threshold: 5
  fallback_strategy: "use_backup_service"

# Configuration errors
ConfigurationError:
  action: "reload_config"
  severity: "medium"
  description: "Invalid or missing configuration"
  auto_fix: true
  retry_count: 2
  retry_delay: 1
  recovery_strategy: "config_reload"
  monitoring:
    enabled: true
    alert: false
  circuit_breaker:
    enabled: false
  fallback_strategy: "use_default_config"

# Validation errors
ValidationError:
  action: "validate_and_retry"
  severity: "medium"
  description: "Data validation failure"
  auto_fix: true
  retry_count: 3
  retry_delay: 1
  recovery_strategy: "validate_and_retry"
  monitoring:
    enabled: true
    alert: false
  circuit_breaker:
    enabled: false
  fallback_strategy: "queue_request"

# Performance errors
PerformanceError:
  action: "optimize"
  severity: "medium"
  description: "Performance degradation detected"
  auto_fix: true
  retry_count: 2
  retry_delay: 5
  recovery_strategy: "cleanup_memory"
  monitoring:
    enabled: true
    alert: true
  circuit_breaker:
    enabled: false
  fallback_strategy: "degrade_features"
  performance_management:
    threshold: 70
    optimize_aggressive: false

# Integration errors
IntegrationError:
  action: "retry"
  severity: "high"
  description: "Integration with external service failed"
  auto_fix: true
  retry_count: 3
  retry_delay: 5
  recovery_strategy: "retry_with_backoff"
  monitoring:
    enabled: true
    alert: true
  circuit_breaker:
    enabled: true
    failure_threshold: 3
  fallback_strategy: "use_cached_data"
  integration_management:
    timeout: 10
    verify_response: true

# Authentication errors
AuthenticationError:
  action: "retry"
  severity: "high"
  description: "Authentication failure"
  auto_fix: true
  retry_count: 2
  retry_delay: 1
  recovery_strategy: "retry_with_backoff"
  monitoring:
    enabled: true
    alert: true
  circuit_breaker:
    enabled: true
    failure_threshold: 3
  fallback_strategy: "use_alternative_auth"
  auth_management:
    max_attempts: 3
    lockout_duration: 300

# Rate limit errors
RateLimitError:
  action: "wait"
  severity: "medium"
  description: "Rate limit exceeded"
  auto_fix: true
  retry_count: 3
  retry_delay: 10
  recovery_strategy: "retry_with_backoff"
  monitoring:
    enabled: true
    alert: false
  circuit_breaker:
    enabled: false
  fallback_strategy: "queue_request"
  rate_limit_management:
    window: 60
    max_requests: 100 